### ISSUE TITLE
Tezos nodes : ops management

### ISSUE THREAD

**Issue by oteku** [marigold-dev/tzstamp#16]
## Depends on

- #14

## Problem

Since we will run our own management we need to document and automatize ops

## Solution

- [ ] Document the setup a node
- [ ] Process and document upgrades
- [ ] Create DNS entries
- [ ] Design and do what could be automatize by CI or tooling

**Comment by fraidev** [comment]
Resolved, less the `Process and document upgrades`. I will create an issue about on infra repo.
